package TestNG;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Reporter;
import org.testng.annotations.Test;

import io.github.bonigarcia.wdm.WebDriverManager;

public class s04ReporterLogTest {
	/**************************************************************
	  Reporter class is used for test methods to log messages.
	  that will be included in the HTML reportsgenerated by TestNG. 
	 **************************************************************/
	@Test()
	public void method1() throws InterruptedException {	
		WebDriverManager.chromedriver().setup();
		WebDriver driver = new ChromeDriver();
		Reporter.log("Chrome browser lunch \n", true);
		
		driver.manage().window().maximize();
		Reporter.log("Browser maximized \n");
		
		driver.get("http://demo.automationtesting.in/Register.html");
		Reporter.log("demo automation url lunched \n", true);
		
		driver.findElement(By.xpath("//input[@placeholder='First Name']")).sendKeys("David");
		Reporter.log("David is enter in the firstName textbox \n");
		
		driver.findElement(By.xpath("//input[@placeholder='Last Name']")).sendKeys("Johnson");
		Reporter.log("Johnson is enter in the lastName textbox \n");
		
		driver.findElement(By.xpath("//input[@id='checkbox1']")).click();
		Reporter.log("cricket checkbox is checked \n");
		
		driver.findElement(By.xpath("//input[@value='Male']")).click();
		Reporter.log("Male radio button is selected \n");
		
		driver.quit();
		//Reporter.log("===amazon.com Lunched ===", true);
	}

}
